version: '3.1'
services:
    webserver:
        image: php:7.3-apache
        restart: always
        volumes:
            - ./html:/var/www/html
        environment:
            - myenvvar="hello"
        ports:
            - "3000:80"